name: macos

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'README.md'

  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'README.md'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v6

      - name: Install Qt macos
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.0'
          modules: 'qtquick3dphysics qtquick3d qtquicktimeline'
          aqtversion: ==3.1.18
          target: desktop
          host: mac

      - name: Build all
        shell: bash -l {0}
        env:
          QT_PATH: /Users/runner/work/DreamMachine/Qt/6.8.0/macos
        run: |
          cd client
          ${{env.QT_PATH}}/bin/qt-cmake --version
          ${{env.QT_PATH}}/bin/qt-cmake -B build/ -G Ninja \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build build/
          cp ../script/create-dmg/build-dmg.sh ./build/build-dmg.sh
          cp ../script/create-dmg/installer_background.png ./build/installer_background.png
          cd ./build
          ${{env.QT_PATH}}/bin/macdeployqt ./DreamMachine.app
          otool -L ./DreamMachine.app/Contents/MacOS/DreamMachine
          sudo ./build-dmg.sh DreamMachine
          cd -
          cp -r ./build/DreamMachine.dmg ../
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          path: |
            DreamMachine.dmg
